# Exploratory Data Analysis (EDA)
Let's check the distribution and statistics of the target and key features in the training data.

In [2]:
# Load training data and show basic statistics
import pandas as pd
train_df = pd.read_csv('../data/train.csv')
print('Shape:', train_df.shape)
print('Columns:', train_df.columns.tolist())
print(train_df[['units_sold']].describe())
print(train_df[['units_sold']].value_counts().head(10))

Shape: (150150, 9)
Columns: ['record_ID', 'week', 'store_id', 'sku_id', 'total_price', 'base_price', 'is_featured_sku', 'is_display_sku', 'units_sold']
          units_sold
count  150150.000000
mean       51.674206
std        60.207904
min         1.000000
25%        20.000000
50%        35.000000
75%        62.000000
max      2876.000000
units_sold
15            3128
18            3024
17            2939
23            2854
21            2843
14            2842
20            2715
12            2690
25            2676
22            2605
Name: count, dtype: int64

In [3]:
# Show statistics for key features
key_features = ['total_price', 'base_price', 'week', 'store_id', 'sku_id']
for col in key_features:
    if col in train_df.columns:
        print(f'--- {col} ---')
        print(train_df[col].describe())
        print(train_df[col].value_counts().head(10))

--- total_price ---
count    150149.000000
mean        206.626751
std         103.308516
min          41.325000
25%         130.387500
50%         198.075000
75%         233.700000
max         562.162500
Name: total_price, dtype: float64
total_price
205.9125    7048
213.0375    5272
177.4125    4544
469.5375    4489
227.2875    4150
327.0375    2975
234.4125    2819
498.0375    2673
106.1625    2392
212.3250    2215
Name: count, dtype: int64
--- base_price ---
count    150150.000000
mean        219.425927
std         110.961712
min          61.275000
25%         133.237500
50%         205.912500
75%         234.412500
max         562.162500
Name: base_price, dtype: float64
base_price
205.9125    7874
469.5375    7084
213.0375    6907
227.2875    6768
498.0375    4421
234.4125    4254
177.4125    3970
327.0375    3336
212.3250    2873
106.1625    2317
Name: count, dtype: int64
--- week ---
count       150150
unique         130
top       17/01/11
freq          1155
Name: week, dtype: object
week
17/01/11    1155
24/01/11    1155
31/01/11    1155
07/02/11    1155
14/02/11    1155
21/02/11    1155
28/02/11    1155
07/03/11    1155
14/03/11    1155
21/03/11    1155
Name: count, dtype: int64
--- store_id ---
count    150150.000000
mean       9199.422511
std         615.591445
min        8023.000000
25%        8562.000000
50%        9371.000000
75%        9731.000000
max        9984.000000
Name: store_id, dtype: float64
store_id
8094    3120
8991    2990
9823    2990
8023    2730
8438    2730
9279    2600
8317    2600
9872    2600
9092    2470
9273    2470
Name: count, dtype: int64
--- sku_id ---
count    150150.000000
mean     254761.132468
std       85547.306447
min      216233.000000
25%      217217.000000
50%      222087.000000
75%      245338.000000
max      679023.000000
Name: sku_id, dtype: float64
sku_id
219009    9750
216233    9620
219029    9490
223245    9490
222087    9360
217390    9100
222765    8970
216418    8840
216419    8710
216425    8580
Name: count, dtype: int64